[package]
name = "pahkat-types"
version = "0.6.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
derive_builder = "0.9.0"
