[package]
name = "pahkat-types"
version = "1.0.0-alpha.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
derive_builder = "0.9.0"
url = { version = "2.1.1", features = ["serde"] }
